#!/usr/bin/env python3
"""Strata ModelGeometry from a HuggingFace config.json.

Strata's engine hardcodes ONE architecture (Qwen3.8-Flash-Next, model_type qwen4_exp_text).
`include/strata/core/layout.hpp` declares that geometry as default member values and
`src/core/layout.cpp::check_layer` asserts every tensor shape against it at load time.

This script maps a config.json onto that struct and prints the C++ block to paste, plus
the deltas that still need hand work. It does not make the engine run another model.

    python tools/geometry_from_config.py config.json          # print C++ block + warnings
    python tools/geometry_from_config.py config.json --check  # exit 1 if unsupported

Self-check (no network, no deps):  python tools/geometry_from_config.py
"""
import argparse
import json
import sys

# What Strata's kernels are written against, from layout.hpp / the Flash-Next config.
STRATA = dict(
    model_type="qwen4_exp_text", n_embd=2560, n_layers=48, qsa_interval=4,
    n_expert=512, n_ff=640, top_k=10,
    hc=4, hc_lr=320,
    idx_q_heads=4, idx_key_dim=128,
    n_head=24, n_head_kv=2, head_dim=256,
    ssm_state_size=128, ssm_k_heads=16, ssm_v_heads=48,
    ssm_d_conv=4, vocab_size=248320,
)


def geom(tc):
    """config text_config -> the fields layout.hpp carries, plus what it does not."""
    lt = tc.get("layer_types") or []
    state, kh, vh = (tc.get("linear_value_head_dim"), tc.get("linear_num_key_heads"),
                      tc.get("linear_num_value_heads"))
    g = {
        "model_type": tc.get("model_type"),
        "n_embd": tc.get("hidden_size"),
        "n_layers": tc.get("num_hidden_layers"),
        "qsa_interval": tc.get("full_attention_interval"),
        "n_expert": tc.get("num_experts"),
        "n_ff": tc.get("moe_intermediate_size") or tc.get("shared_expert_intermediate_size"),
        "top_k": tc.get("num_experts_per_tok"),
        "hc": tc.get("hc_count"),
        "hc_lr": tc.get("hc_lowrank"),
        "idx_q_heads": tc.get("indexer_n_heads"),
        "idx_key_dim": tc.get("indexer_head_dim"),
        "n_head": tc.get("num_attention_heads"),
        "n_head_kv": tc.get("num_key_value_heads"),
        "head_dim": tc.get("head_dim"),
        "ssm_state_size": state,
        "ssm_k_heads": kh,
        "ssm_v_heads": vh,
        "ssm_d_conv": tc.get("linear_conv_kernel_dim"),
        "vocab_size": tc.get("vocab_size"),
        # 2*state*k_heads + state*v_heads, the GDN conv input width layout.hpp hardcodes
        "ssm_conv_channels": 2 * (state or 0) * (kh or 0) + (state or 0) * (vh or 0),
        "ssm_value_dim": (state or 0) * (vh or 0),
        "_dense_layers": sum(1 for t in lt if t == "linear_attention"),
        "_full_layers": sum(1 for t in lt if t == "full_attention"),
        "_has_ple": "ngram_size" in tc,
    }
    return g


def deltas(g):
    """What a human still has to write, as (field, strata, target, why)."""
    out = []
    for k in ("model_type", "n_embd", "n_layers", "qsa_interval", "n_expert", "n_ff", "top_k",
              "n_head", "n_head_kv", "head_dim", "ssm_state_size", "ssm_k_heads",
              "ssm_v_heads", "vocab_size"):
        if g[k] != STRATA[k]:
            out.append((k, STRATA[k], g[k], "geometry"))

    # Feature gates: absent in config means the tensor set changes, which check_layer asserts.
    if g["hc"] is None:
        out.append(("hc / hc_lr", f'{STRATA["hc"]}/{STRATA["hc_lr"]}', "absent",
                    "no gated residual -> drop the 6 hc_* tensors from Want2"))
    if g["idx_q_heads"] is None:
        out.append(("indexer.*", f'{STRATA["idx_q_heads"]}x{STRATA["idx_key_dim"]}', "absent",
                    "no QSA indexer -> every full-attention layer needs full attention, not qsa_*"))
    if g["n_expert"] is None:
        out.append(("MoE", f'{STRATA["n_expert"]} experts', "absent",
                    "dense FFN -> shared_expert path only, gate_inp is [n_embd, n_ff]"))
    if not g["_has_ple"]:
        out.append(("PLE n-gram", "present", "absent",
                    "no ngram table -> spec/ + ngram/ + ple_* kernels are dead code for this pack"))
    return out


def cpp_block(g):
    return f"""// generated by tools/geometry_from_config.py - paste into ModelGeometry's defaults
    int64_t n_embd = {g['n_embd']};
    int64_t n_layers = {g['n_layers']};
    int64_t qsa_interval = {g['qsa_interval']};   // {g['_full_layers']} full / {g['_dense_layers']} linear

    // GDN
    int64_t ssm_state_size = {g['ssm_state_size']};
    int64_t ssm_k_heads = {g['ssm_k_heads']};
    int64_t ssm_v_heads = {g['ssm_v_heads']};
    int64_t ssm_d_conv = {g['ssm_d_conv']};
    int64_t ssm_conv_channels = {2 * (g['ssm_state_size'] or 0) * (g['ssm_k_heads'] or 0) + (g['ssm_state_size'] or 0) * (g['ssm_v_heads'] or 0)};
    int64_t ssm_value_dim = {(g['ssm_state_size'] or 0) * (g['ssm_v_heads'] or 0)};

    // attention
    int64_t n_head = {g['n_head']};
    int64_t n_head_kv = {g['n_head_kv']};
    int64_t head_dim = {g['head_dim']};"""


def demo():
    """The mapping itself, checked against Strata's own Flash-Next numbers."""
    tc = dict(model_type="qwen4_exp_text", hidden_size=2560, num_hidden_layers=48,
              full_attention_interval=4, num_experts=512, moe_intermediate_size=640,
              num_experts_per_tok=10, hc_count=4, hc_lowrank=320, indexer_n_heads=4,
              indexer_head_dim=128, num_attention_heads=24, num_key_value_heads=2,
              head_dim=256, linear_value_head_dim=128, linear_num_key_heads=16,
              linear_num_value_heads=48, linear_conv_kernel_dim=4, vocab_size=248320,
              ngram_size=3, layer_types=["linear_attention"] * 36 + ["full_attention"] * 12)
    g = geom(tc)
    assert g["ssm_conv_channels"] == 10240, g["ssm_conv_channels"]   # 2*128*16 + 128*48
    assert g["ssm_value_dim"] == 6144, g["ssm_value_dim"]
    assert (g["_dense_layers"], g["_full_layers"]) == (36, 12)
    assert not [d for d in deltas(g) if d[0] not in ("model_type",)], deltas(g)
    # a config with no MoE and no indexer must say so
    dense = geom({k: v for k, v in tc.items() if k not in ("num_experts", "moe_intermediate_size",
                                                            "num_experts_per_tok", "indexer_n_heads",
                                                            "indexer_head_dim", "hc_count", "hc_lowrank")})
    fields = {d[0] for d in deltas(dense)}
    assert "indexer.*" in fields and "hc / hc_lr" in fields and "MoE" in fields, fields
    print("demo ok")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("config", nargs="?")
    ap.add_argument("--check", action="store_true", help="exit 1 when hand work is needed")
    a = ap.parse_args()
    if not a.config:
        return demo()
    raw = json.load(open(a.config, encoding="utf-8"))
    g = geom(raw.get("text_config", raw))
    print(cpp_block(g))
    d = deltas(g)
    if not d:
        print("\nno delta vs Strata's Flash-Next geometry")
        return 0
    print("\nstill hand work:")
    for f, s, t, why in d:
        print(f"  {f:<22} {str(s):<16} -> {str(t):<12} {why}")
    return 1 if a.check else 0


if __name__ == "__main__":
    sys.exit(main())